services:
  caddy:
    image: caddy:2-alpine
    hostname: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "80:80"
    depends_on:
      - chipend
      - iceprxy-chiptune
      - iceprxy-vapor

  chipend:
    image: ruohki/chipend
    build:
      context: chipend/
      dockerfile: Dockerfile

  iceprxy-chiptune:
    image: ruohki/iceprxy
    build:
      context: iceprxy/
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - STREAM_URL=http://79.120.11.40:8000/chiptune.ogg

  iceprxy-vapor:
    image: ruohki/iceprxy
    build:
      context: iceprxy/
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - STREAM_URL=http://79.120.11.40:8000/vapor.ogg

  icecast:
    image: moul/icecast
    environment:
      ICECAST_ADMIN_PASSWORD: adminpassword
      ICECAST_SOURCE_PASSWORD: sourcepassword
    restart: unless-stopped
    depends_on:
      - caddy

  transcoder-chip:
    image: jrottenberg/ffmpeg:4.4-alpine
    command: >
      -re -i http://79.120.11.40:8000/chiptune.ogg
      -c:a libmp3lame -b:a 128k -content_type audio/mpeg
      -f mp3
      icecast://source:sourcepassword@icecast:8000/chip.mp3
    depends_on:
      - caddy
      - icecast
    restart: unless-stopped
  transcoder-vapor:
    image: jrottenberg/ffmpeg:4.4-alpine
    command: >
      -re -i http://79.120.11.40:8000/vapor.ogg
      -c:a libmp3lame -b:a 128k -content_type audio/mpeg
      -f mp3
      icecast://source:sourcepassword@icecast:8000/vapor.mp3
    depends_on:
      - icecast
      - caddy
    restart: unless-stopped