services:
  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - chipend

  chipend:
    image: ruohki/chipend
    build:
      context: chipend/
      dockerfile: Dockerfile

  icecast:
    image: moul/icecast
    environment:
      - ICECAST_ADMIN_PASSWORD
      - ICECAST_SOURCE_PASSWORD
    restart: unless-stopped
    depends_on:
      - caddy

  transcoder-chip:
    image: jrottenberg/ffmpeg:4.4-alpine
    command: >
      -re -i https://cast.ruohki.services/chiptune.ogg
      -c:a libmp3lame -b:a 128k -content_type audio/mpeg
      -f mp3 $CHIP_ICECAST_URL
    environment:
      - CHIP_ICECAST_URL
    depends_on:
      - caddy
      - icecast
    restart: unless-stopped
  transcoder-vapor:
    image: jrottenberg/ffmpeg:4.4-alpine
    command: >
      -re -i https://cast.ruohki.services/vapor.ogg
      -c:a libmp3lame -b:a 128k -content_type audio/mpeg
      -f mp3 $VAPOR_ICECAST_URL
    environment:
      - VAPOR_ICECAST_URL
    depends_on:
      - icecast
      - caddy
    restart: unless-stopped